name: build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:  # Allow manual trigger button
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/publish.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/publish.yml'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  # <account>/<repo>

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_CLASSIC_GITHUB_DOCKER_BUILD_READ_WRITE }}

      # Extract metadata (tags, labels) for Docker (https://github.com/docker/metadata-action)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build but don't push Docker image with Buildx (https://github.com/docker/build-push-action)
      - name: Build (but not push) Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: false
          tags: ${{ github.event.repository.name }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}  # From Dockerfile lines eg: `LABEL maintainer="Your Name <your.email@example.com>"`
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Load the built image into Docker instead of pushing it to a registry
          # This allows us to test it out in the next step.
          load: false  # change to true if you want to run the image in the next step

      # - name: Run the image
      #   run: docker run --rm ${{ github.event.repository.name }}:${{ github.sha }} pwd
